# Generated by Django 5.2.16 on 2026-07-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0005_productvarientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvarientmodel'),
        ),
    ]
