# Generated by Django 5.2.16 on 2026-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitemmodel_variant'),
        ('shop', '0005_productvarientmodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitemmodel',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='unique_cart_product_variant'),
        ),
    ]
