# Generated by Django 5.2.17 on 2026-08-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productmodel_category'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('image', models.ImageField(default='default/default.png', upload_to='blog/images/')),
                ('image_alt_text', models.CharField(blank=True, max_length=255)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('reading_time', models.PositiveIntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'نمایش'), (2, 'پیش\u200cنویس')], default=2)),
                ('views', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='website.blogcategorymodel')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_blogs', to='shop.productmodel')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
