# Generated by Django 5.2.16 on 2026-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='product/img/'),
        ),
    ]
