# Generated by Django 5.2.16 on 2026-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای نتایج گوگل. حداکثر ۱۵۵-۱۶۰ کاراکتر.', max_length=160),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='meta_title',
            field=models.CharField(blank=True, help_text='اگه خالی بمونه از title استفاده می\u200cشه. حداکثر ۶۰-۷۰ کاراکتر.', max_length=70),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='متن جایگزین تصویر برای سئو. مثلاً: خرید بوم نقاشی سایز A3', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
