# Generated by Django 5.2.16 on 2026-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_fix_varient_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarientmodel',
            name='color_code',
            field=models.CharField(blank=True, help_text="فقط برای نوع 'رنگ' پر کن. کد هگز، مثلاً 12", max_length=7, null=True),
        ),
    ]
