# Generated by Django 5.2.16 on 2026-08-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productvarientmodel_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط اگه این شماره/سایز قیمتش با قیمت پایه محصول فرق داره پر کن. خالی بمونه یعنی از قیمت محصول استفاده میشه.', max_digits=10, null=True),
        ),
    ]
