# Generated by Django 5.2.16 on 2026-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productbrandmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ManyToManyField(to='shop.productbrandmodel'),
        ),
    ]
