# Generated by Django 5.2.16 on 2026-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productvarientmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientmodel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='این وریانت همون رنگ/سایزیه که خودِ این محصول نشون میده. اگه کاربر از پالت چیزی انتخاب نکنه، همین به\u200cصورت خودکار انتخاب میشه.'),
        ),
    ]
