# Generated by Django 5.2.16 on 2026-08-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productvarientmodel_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarientmodel',
            name='is_default',
        ),
    ]
