# Generated by Django 5.2.16 on 2026-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_productmodel_brand_productmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(related_name='products', to='shop.productcategorymodel'),
        ),
    ]
