# Generated by Django 5.2.17 on 2026-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط اگه این شماره/سایز/رنگ قیمتش با قیمت پایه محصول فرق داره پر کن. خالی بمونه یعنی از قیمت محصول استفاده میشه.', max_digits=10, null=True),
        ),
    ]
