# Generated by Django 5.2.17 on 2026-08-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productvarientmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='image',
            field=models.ImageField(default='default/faber-castell.webp', upload_to='brands/img/'),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='image',
            field=models.ImageField(default='default/آبرنگ.webp', upload_to='categories/img/'),
        ),
    ]
