# Generated by Django 5.2.17 on 2026-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productbrandmodel_image_productcategorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
