# Generated by Django 5.2.17 on 2026-08-11 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productbrandmodel_image_productcategorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientmodel',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='درصد تخفیف مخصوص همین سایز/رنگ. اگه صفر باشه از تخفیف محصول اصلی استفاده میشه.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='productvarientmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='موجودی مخصوص همین سایز/رنگ'),
        ),
    ]
