# Generated by Django 5.2.17 on 2026-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productcategorymodel_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='baner_image',
            field=models.ImageField(default='default/cat-abner-3.webp', upload_to='cat-baners/img/'),
        ),
    ]
