# Generated by Django 5.2.17 on 2026-08-11 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productvarientmodel_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=1, help_text='نمایش یا عدم نمایش همین سایز/رنگ به صورت مجزا'),
        ),
        migrations.AlterField(
            model_name='productvarientmodel',
            name='color_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='productvarientmodel',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='درصد تخفیف مخصوص همین سایز/رنگ', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productvarientmodel',
            name='number_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productvarientmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='قیمت مخصوص همین سایز/رنگ', max_digits=10),
            preserve_default=False,
        ),
    ]
