# Generated by Django 5.2.17 on 2026-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productcategorymodel_baner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='h3_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='p_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
