# Generated by Django 5.2.17 on 2026-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productcategorymodel_h3_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='baner',
            field=models.BooleanField(default=False),
        ),
    ]
