# Generated by Django 5.2.17 on 2026-08-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productmodel_discount_percent_and_more'),
        ('shop', '0018_productcategorymodel_baner'),
    ]

    operations = [
    ]
