# Generated by Django 5.2.17 on 2026-08-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_merge_20260811_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rate',
        ),
    ]
