# Generated by Django 5.2.17 on 2026-08-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_productmodel_avg_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'ordering': ['created_date']},
        ),
    ]
