# Generated by Django 5.2.17 on 2026-08-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_productimagemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان ویژگی، مثلاً: برند', max_length=100)),
                ('description', models.CharField(help_text='مقدار ویژگی، مثلاً: وستا', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='shop.productmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSpecModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان ویژگی، مثلاً: طول قلمو', max_length=100)),
                ('description', models.CharField(help_text='مقدار ویژگی، مثلاً: ۱۸ سانتی\u200cمتر', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='shop.productvarientmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
