# Generated by Django 5.2.17 on 2026-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productspecmodel_productvariantspecmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarientmodel',
            name='variant_type',
            field=models.CharField(choices=[('color', 'رنگ (ویستا)'), ('pars_color', 'رنگ (پالت پارس)'), ('number', 'شماره')], help_text="نوع تنوع: اگه رنگه 'رنگ' انتخاب کن، اگه شماره\u200cس (مثل قلمو) 'شماره' انتخاب کن", max_length=20),
        ),
    ]
