# Generated by Django 5.2.17 on 2026-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_productvarientmodel_variant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandmodel',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
