# Generated by Django 5.2.17 on 2026-08-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_productbrandmodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=2),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=2),
        ),
    ]
