# Generated by Django 5.2.17 on 2026-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_productbrandmodel_status_productcategorymodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarientmodel',
            name='number_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
