# Generated by Django 5.2.16 on 2026-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressmodel',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
