# Generated by Django 5.2.16 on 2026-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_useraddressmodel_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
