# Generated by Django 5.2.16 on 2026-07-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_zip_code_alter_ordermodel_address'),
        ('shop', '0005_productvarientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsmodel',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvarientmodel'),
        ),
    ]
