# Generated by Django 5.2.17 on 2026-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitemsmodel_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsmodel',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitemsmodel',
            name='original_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='copon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='copon_discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
