# Generated by Django 5.2.17 on 2026-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitemsmodel_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'پرداخت شده'), (3, 'پردازش'), (4, 'در حال آماده\u200cسازی'), (5, 'تحویل پست مبدا داده شد'), (6, 'لغو شده')], default=1),
        ),
    ]
