# Generated by Django 5.2.17 on 2026-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitemsmodel_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=190000, verbose_name='قیمت پست (تومان)')),
            ],
        ),
    ]
