# Generated by Django 5.2.17 on 2026-09-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_ordermodel_status'),
        ('order', '0009_postprice'),
    ]

    operations = [
    ]
