# Generated by Django 5.2.17 on 2026-09-21 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_merge_0009_alter_ordermodel_status_0009_postprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='stock_reserved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حال پرداخت'), (2, 'پرداخت شده'), (3, 'پردازش شده'), (4, 'در حال آماده\u200cسازی'), (5, 'تحویل پست مبدا داده شد'), (6, 'لغو شده')], default=1),
        ),
        migrations.AddConstraint(
            model_name='ordermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('user',), name='one_pending_order_per_user'),
        ),
    ]
