# Generated by Django 5.2.17 on 2026-08-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0007_alter_orderitemsmodel_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار'), (2, 'پرداخت موفق'), (3, 'پرداخت ناموفق')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.ordermodel')),
            ],
            options={
                'ordering': ['-created_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('order',), name='one_pending_payment_per_order')],
            },
        ),
    ]
