# Generated by Django 5.2.17 on 2026-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='card_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='card_pan',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='authority_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
